version: "2"
services:
  zhang-htpasswd-registry:
    image: registry:2.5
    ports:
      -  "5000:5000"
    volumes:
      - /pwd/auth:/auth
      - /pwd/cert:/certs
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry_auth.crt
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_HTTP_TLS_KEY=/certs/registry_auth.key
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd