version: "2"
services:
  htpasswd:
    image: index.alaua.cn/alaudak8s/docker-htpasswd-registry:v1
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry_auth.crt
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_HTTP_TLS_KEY=/certs/registry_auth.key
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd